### ISSUE TITLE
Derive or impl std::fmt::Debug for both flavors

### ISSUE THREAD

**Issue by Deewiant** [dcrewi/rust-mersenne-twister#3]
Neither `MT19937` nor `MT19937_64` implement the [`std::fmt::Debug`](https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html) trait, which means that they can't be directly embedded in structs that derive `Debug`.

All the generators in the [`rand`](https://doc.rust-lang.org/rand/rand/index.html) crate simply derive `Debug` so I don't think there's any reason why the MT generators couldn't do the same.

**Comment by dcrewi** [comment]
It looks like the reason I didn't derive `Debug` in the first place is because `[u32; 624]` isn't `Debug`. I then left the problem for another time. It's the same story with (`Partial`)`Eq`, (`Partial`)`Ord`, and `Hash`. I will consider what to do.

**Comment by dcrewi** [comment]
Crate version 1.1.0 now has a `Debug` implementation. Thanks for the feedback!

**Comment by Deewiant** [comment]
Thanks for the quick response! And good call on the other traits.
